.TH fwkit 8
.SH NAME
fwkit \- Firewall Kit for modular firewalls
.SH SYNOPSIS
\fBfwkit rules\fR { \fBclean\fR | \fBcompile\fR | \fBload\fR | \fBreload\fR | \fBunload\fR }
.br
\fBfwkit service\fR { \fBdisable\fR | \fBenable\fR } { \fBlocal\fR } \fIservice\fR ...
.br
\fBfwkit service list\fR
.br
\fBfwkit role\fR { \fBget\fR | \fBlist\fR }
.br
\fBfwkit role set \fIrole\fR
.br
.fBfwkit role\fR { \fBdefine\fR | \fBundefine\fR } \fIrole\fR [ \fIdescription\fR ]
.br
\fBfwkit zone\fR { \fBdefine | \fBundefine\fR } \fIzone source\R [ \FIdescription\fR ]
.br
\fBfwkit zone list\fR
.br
\fBfwkit config get\fR [ \fIvar\fR ]
.br
\fBfwkit config set \fIvar value\fR
.br
\fBfwkit config unset \fIvar\fR
.SH DESCRIPTION
fwkit is primarily designed around the concept of roles and services. Roles maintain a collection of enabled services. A ruleset is compiled based on the services enabled for the active role. Roles can be customized to suit any need, and a number of roles are configured by default.
.SH OPTIONS
.TP
.B rules
Rule management.
.RS
.TP .4i
.B clean
Remove any compiled or cached rules.
.TP .4i
.B compile
Prepare the ruleset for loading.
.TP .4i
.B load
Load the ruleset. If a cached rulset is available, load it. If a compiled ruleset is available, load it, otherwise compile it first.
.TP .4i
.B reload
A shortcut for running \fBunload\fR, \fBclean\fR, \fBcompile\fR, \fBload\fR.
.TP .4i
.B unload
Unload the rulset. The live ruleset is cached using
.BR iptables-save (8).
.RE
.TP
\fBservice\fR|\fBservices\fR
Service management.
.RS
.TP .4i
\fBdisable\fR { \fBlocal\fR | \fBremote\fR } \fIservice\fR ...
Disable a \fBlocal\fR or \fBremote\fR \fIservice\fR. More than one service can be specified.
.TP .4i
\fBenable\fR { \fBlocal\fR | \fBremote\fR } \fIservice\fR ...
Enable a \fBlocal\fR or \fBremote\fR \fIservice\fR. More than one service can be specified.
.TP .4i
\fBlist\fR
List all services along with their state (enabled or disabled).
.RE
.TP
\fBrole\fR|\fBroles\fR
Role management.
.RS
.TP .4i
.B get
Get the current role.
.TP .4i
.B list
List the available roles. The active role is marked with an asterisk.
.TP .4i
\fBset \fIrole\fR
Set the active role to \fIrole\fR.
.TP .4i
.B define
Define a new role \fIrole\fR, with optional description \fIdescription\fR.
.TP .4i
.B undefine
Undefine (delete) an existing role \fIrole\fR.
.RE
.TP
\fBzone\fR|\fBzones\fR
Zone management.
.RS
.TP .4i
.B define
Define a new zone \fIzone\fR for the currently enabled role, from network or host address \fIsource\fR, with optional description \fIdescription\fR.
.TP .4i
.B undefine
Undefine an existing zone \fIzone\fR for the currently enabled role.
.TP .4i
.B list
List the zones for the currently enabled role.
.RE
.TP
\fBconfig\fR
Configuration management. Configuration variables consist of two classes: \fBcore\fR and \fBvars\fR. \fBcore\fR variables are used internally by fwkit to modify it's behaviour. \fBvars\fR are made available to the ruleset and are used to allow for more dynamic configuration. \fIvar\fR refers to the full variable name, i.e.
\fIclass\fR.\fIname\fR. The \fIname\fR portion can only contain numbers, letters, and underscores.  Examples of variable names are: \fBcore.interpreter\fR, \fBvars.foo_bar\fR, \fBvars.funkyChicken\fR.
.RS
.TP .4i
\fBget\fR [ \fIvar\fR ]
Get the value of configuration variable \fIvar\fR.
.TP .4i
\fBset\fR \fIvar\fR \fIvalue\fR
Set the value of configuration variable \fIvar\fR to \fIvalue\fR.
.TP .4i
\fBunset \fIvar\fR
Unset the configuration variable \fIvar\fR.
.RE
.SH ZONE MANAGEMENT
Roles are created with a single zone called "default". Additional zones can be defined for a role to segment traffic from differnet networks and/or interfaces, allowing services to be enabled or disabled independently for these segments. For example:
.P
.in +7
fwkit zone define lan 192.168.0.0/24
fwkit services enable local lan:ssh lan:smb lan:dhcp
.P
When services are enabled or disable for a zone other then the "default" zone, they must be prepended with the zone name followed by a colon ":".
.SH SIMPLE PORT FOWARDING
fwkit provides a convenient shorcut for defining port forwarding configurations. \fBvars\fR-class variables beginning with \fBdnat_\fR are treated by the ruleset as port-forwarding definitions and the appropriate rules are generated to execute the definition. A port forwarding definition is as follows:
.P
.in +7
{ \fBtcp\fR | \fBudp\fR } / [ \fIsrc\fR ] \fB:\fIsrcport\fR / \fIdst\fR [ \fB:\fIdstport\fR ]
.RS
.TP .4i
.I src
The source IP address. This is optional, and if omitted all source IP's will match.
.TP .4i
.I srcport
The source port number.
.TP .4i
.I dst
The destination IP address.
.TP .4i
.I dstport
The destination port number. This is optional, and if omitted \fIsrcport\fR will be used.
.RE
.P
To redirect SSH connections on port 2202 to the local daemon listening on localhost port 22, the port forwarding definition would look like:
.P
.in +7
tcp/:2202/127.0.0.1:22
.P
To create the port-forward definition above, set the configuration variable and then reload the ruleset:
.P
.in +7
fwkit config set vars.dnat_ssh tcp/:2202/127.0.0.1:22
.br
fwkit rules reload
.P
.in -7
.SH FILES
.TP
/etc/fwkit/roles/\fIrole\fR/policy.rules
The first file included during compilation, appropriate for setting chain policies.
.TP
/etc/fwkit/rules.d/pre/*.rules
Files containing rules to be included before service definitions.
.TP
/etc/fwkit/rules.d/post/*.rules
Files containing rules to be included after service definitions.
.TP
/etc/fwkit/services/local/*.service
Local service definitions.
.TP
/etc/fwkit/services/remote/*.service
Remote service definitions.
.SH SEE ALSO
/usr/share/fwkit/Readme.md
.SH AUTHOR
Matt Ferris <matt@bueller.ca>
