#!/bin/sh

myname=$( basename $0 )

etcdir=/etc/fwkit
libdir=/var/lib/fwkit

mode=$1
action=$2

if [ ! -z "$FWKIT_ETCDIR" ]; then
    etcdir=$FWKIT_ETCDIR
fi

if [ ! -z "$FWKIT_LIBDIR" ]; then
    libdir=$FWKIT_LIBDIR
fi

confload() {
    type=$1
    prefix=$2
    for i in $(find "$etcdir/conf/$type" -type f); do
        name=$(basename $i)
        eval "export $prefix$name=\"$(cat $i)\""
    done
}

confenv() {
    type=$1
    prefix=$2
    for i in $(find "$etcdir/conf/$type" -type f); do
        name=$(basename $i)
        value=$(eval echo $(cat $i))
        echo -n "$prefix$name=$value "
    done
}

doerror() {
    echo "error: $2" 1>&2
    exit $1
}

donotice() {
    echo "notice: $1" 1>&2
}

confload core core_

case $mode in

    rules)

        #
        # All actions related to rules mode
        #

        case $action in

            clean)
                for i in $( ls -1 "$libdir" ); do
                    rm "$libdir/$i"
                done
	        ;;

            compile)
                if [ -f "$libdir/compile.tmp" ]; then
                    rm "$libdir/compiled.tmp"
                fi

                if [ ! -d "$etcdir" ]; then
                    doerror 1 "config directory $etcdir doesn't exist or isn't a directory"
                fi

                if [ ! -e "$etcdir/role.active" ]; then
                    doerror 1 "no role specified"
                fi

                # include role policy if it exists
                policy="$etcdir/role.active/policy.rules"
                if [ -f "$policy" ]; then
                    echo "#\n# $policy\n#\n" >> $libdir/compiled.tmp
                    cat "$policy" >> "$libdir/compiled.tmp"
                fi

                # include pre-service rules
                if [ -d "$etcdir/rules.d/pre" ]; then
                    for i in $( find "$etcdir/rules.d/pre" -name "*.rules" ); do
                        echo "\n#\n# $i\n#\n" >> $libdir/compiled.tmp
                        cat "$i" >> "$libdir/compiled.tmp"
                    done
                fi

                # include local service rules
                for zone in $( ls -1 "$etcdir/role.active/zones" ); do
                    locsrv="$etcdir/role.active/zones/$zone/services/local"
                    if [ -d "$locsrv" ]; then
                        for i in $( find "$locsrv" -name "*.service" ); do
                            echo "\n#\n# $i\n#\n" >> "$libdir/compiled.tmp"
                            if [ -x "$i" ]; then
                                "$i" $zone local >> "$libdir/compiled.tmp"
                            else
                                cat "$i" >> "$libdir/compiled.tmp"
                            fi
                        done
                    fi
                done

                # include remote service rules
                for zone in $( ls -1 "$etcdir/role.active/zones" ); do
                    rmtsrv="$etcdir/role.active/zones/$zone/services/remote"
                    if [ -d "$rmtsrv" ]; then
                        for i in $( find "$rmtsrv" -name "*.service" ); do
                            echo "\n#\n# $i\n#\n" >> "$libdir/compiled.tmp"
                            if [ -x "$i" ]; then
                                "$i" $zone remote >> "$libdir/compiled.tmp"
                            else
                                cat "$i" >> "$libdir/compiled.tmp"
                            fi
                        done
                    fi
                done

                # include post-service rules
                if [ -d "$etcdir/rules.d/post" ]; then
                    for i in $( find "$etcdir/rules.d/post" -name "*.rules" ); do
                        echo "\n#\n# $i\n#\n" >> $libdir/compiled.tmp
                        cat "$i" >> "$libdir/compiled.tmp"
                    done
                fi

                if [ ! -f "$libdir/compiled.tmp" ]; then
                    donotice "no rules found!"
                fi

                mv "$libdir/compiled.tmp" "$libdir/compiled.rules"

                if [ -f "$libdir/cached.rules" ]; then
                    rm "$libdir/cached.rules"
                fi

                echo "compiled rules into $libdir/compiled.rules"
                ;;

            load)

                if [ -f "$libdir/cached.rules" ]; then
                    echo -n "loading cached rules..."
                    /sbin/iptables-restore < "$libdir/cached.rules"
                    echo "done"
                else
                    if [ ! -f "$libdir/compiled.rules" ]; then
                        $0 rules compile
                    fi

                    echo -n "loading compiled rules..."

                    (
                        # get interface values
                        ip -4 -o addr | grep inet | {
                            while read def; do
                                if=$(echo $def | cut -d' ' -f2)
                                net=$(echo $def | awk '{print $4}')
                                addr=$(echo $net | cut -d/ -f1)
                                eval "export if_${if}_net=\"$net\""
                                eval "export if_${if}_addr=\"$addr\""
                            done

                            env -i FWKIT_ETCDIR=$etcdir FWKIT_LIBDIR=$libdir fwkit=$0 $(confenv vars) $core_interpreter "$libdir/compiled.rules"
                        }
                    )

                    echo "done"
                fi
                ;;

            reload)
                $0 rules unload && $0 rules clean && $0 rules load
                ;;

            unload)
                /sbin/iptables-save > "$libdir/cached.rules"

                iptables -P INPUT ACCEPT
                iptables -P OUTPUT ACCEPT
                iptables -P FORWARD ACCEPT
                iptables -F -t filter
                iptables -F -t nat
                iptables -F -t mangle
                iptables -F -t raw
                iptables -F -t security
                iptables -X

                echo "rules unloaded"
                ;;

            *)
                echo
                echo "usage: $myname rules { action }"
                echo
                echo "Available actions:"
                echo
                echo "    clean   Clear the cached ruleset"
                echo "    compile Compile the rules but don't load them"
                echo "    load    Load the ruleset (compile if cached rules aren't available)"
                echo "    reload  Unload, clean, and load the ruleset"
                echo "    unload  Cached the loaded ruleset and unload it"
                echo
                exit 1
                ;;

        esac
        ;;

    role|roles)

        #
        # all actions related to role mode
        #

        if [ -h "$etcdir/role.active" ]; then
            role=$( basename $(readlink "$etcdir/role.active") )
        fi


        case $action in

            list)
                if [ ! -d "$etcdir/roles" ]; then
                    doerror 1 "roles directory $etcdir/roles doesn't exist"
                fi

                for i in $( ls -1 "$etcdir/roles"); do
                    if [ "$i" = "$role" ]; then
                        echo -n "* "
                    else
                        echo -n "  "
                    fi
                    echo $i
                done

                ;;

            set)
                newrole=$3
                if [ -z "$newrole" ]; then
                    doerror 1 "no new role specified"
                fi

                if [ ! -d "$etcdir/roles/$newrole" ]; then
                    doerror 1 "new role $newrole doesn't exist"
                fi

                if [ -h "$etcdir/role.active" ]; then
                    rm "$etcdir/role.active"
                fi

                ln -s "roles/$newrole" "$etcdir/role.active"

                if [ -z "$role" ]; then
                    role="(none)"
                fi

                echo "role changed: $role -> $newrole"
                ;;

            get)
                if [ -z "$role" ]; then
                    doerror 1 "no active role specified"
                fi
                echo "$role"
                ;;

            *)
                echo
                echo "usage: $myname role { action }"
                echo
                echo "Available actions:"
                echo
                echo "    get       Get the current role"
                echo "    list      List available roles"
                echo "    set       Set the current role"
                echo
                exit 1
                ;;

        esac
        ;;

    service|services)

        #
        # All actions related to service mode
        #

        case $action in

            disable)

                type=$3
                service=$4

                shift; shift

                if [ ! "$type" = "local" -a ! "$type" = "remote" ]; then
                    doerror 1 "invalid service type $type, must be 'local' or 'remote'"
                fi

                if [ -z "$service" ]; then
                    doerror "no service specified"
                fi

                services=""
                while shift; do

                    if [ -z "$1" ]; then
                        break
                    fi

                    service=$1
                    zone="default"

                    if [ ! -z "$(echo $service | grep -e '.:.')" ]; then
                        zone=$(echo $service | cut -d: -f1)
                        service=$(echo $service | cut -d: -f2)
                    fi

                    if [ ! -f "$etcdir/services/$type/$service.service" ]; then
                        doerror 1 "$type service $service doesn't exist"
                    fi

                    if [ ! -d "$etcdir/role.active/zones/$zone/services/$type" ]; then
                        doerror 1 "directory $etcdir/role.active/zones/$zone/services/$type doesn't exist"
                    fi

                    if [ ! -h "$etcdir/role.active/zones/$zone/services/$type/$service.service" ]; then
                        doerror 1 "$type service $service already disabled for zone $zone"
                    fi

                    rm "$etcdir/role.active/zones/$zone/services/$type/$service.service"
                    services="$services $service"

                done

                echo "disabled $type service(s)$services"

                ;;

            enable)

                type=$3
                service=$4

                shift; shift

                if [ ! "$type" = "local" -a ! "$type" = "remote" ]; then
                    doerror 1 "invalid service type $type, must be 'local' or 'remote'"
                fi

                if [ -z "$service" ]; then
                    doerror 1 "no service specified"
                fi

                services=""
                while shift; do

                    if [ -z "$1" ]; then
                        break
                    fi

                    service=$1
                    zone="default"

                    if [ ! -z "$(echo $service | grep -e '.:.')" ]; then
                        zone=$(echo $service | cut -d: -f1)
                        service=$(echo $service | cut -d: -f2)
                    fi

                    if [ ! -f "$etcdir/services/$type/$service.service" ]; then
                        doerror 1 "$type service $service doesn't exist"
                    fi

                    if [ ! -d "$etcdir/role.active/zones/$zone/services/$type" ]; then
                        doerror 1 "directory $etcdir/role.active/zones/$zone/services/$type doesn't exist"
                    fi

                    if [ -h "$etcdir/role.active/zones/$zone/services/$type/$service.service" ]; then
                        doerror 1 "$type service $service already enabled for zone $zone"
                    fi

                    ln -s "$etcdir/services/$type/$service.service" "$etcdir/role.active/zones/$zone/services/$type"

                    services="$services $service"

                done

                echo "enabled $type service(s)$services"

                ;;

            list)

                zone=$3

                if [ -z "$zone" ]; then
                    zone="default"
                fi

                if [ ! -d "$etcdir/role.active/zones/$zone" ]; then
                    doerror 1 "zone not defined '$zone'"
                fi

                printf '\n%s\n' "ZONE $zone"

                printf '\n%s\n' 'LOCAL SERVICES'
                printf '%-7s%-15s%s\n\n' Active Name Description

                for i in $( find "$etcdir/services/local/" -type f -printf "%P\n" | sort ); do
                    if [ -h "$etcdir/role.active/zones/$zone/services/local/$i" ]; then
                        printf '%7s' '* '
                    else
                        echo -n "       "
                    fi

                    short=$( echo -n $i | sed s/.service// )
                    printf '%-15s' "$short"

                    if [ -x "$etcdir/services/local/$i" ]; then
                        desc=$( head -n2 "$etcdir/services/local/$i" | tail -n1 | awk -F' - ' '{print $3}' )
                    else
                        desc=$( head -n1 "$etcdir/services/local/$i" | awk -F' - ' '{print $3}' )
                    fi

                    if [ ! -z "$desc" ]; then
                        echo -n "$desc"
                    fi

                    echo
                done

                printf '\n%s\n' 'REMOTE SERVICES'
                printf '%-7s%-15s%s\n\n' Active Name Description

                for i in $( find "$etcdir/services/remote/" -type f -printf "%P\n" | sort ); do
                    if [ -h "$etcdir/role.active/zones/$zone/services/remote/$i" ]; then
                        printf '%7s' '* '
                    else
                        echo -n "       "
                    fi

                    short=$( echo -n $i | sed s/.service// )
                    printf '%-15s' "$short"

                    if [ -x "$etcdir/services/local/$i" ]; then
                        desc=$( head -n2 "$etcdir/services/local/$i" | tail -n1 | awk -F' - ' '{print $3}' )
                    else
                        desc=$( head -n1 "$etcdir/services/local/$i" | awk -F' - ' '{print $3}' )
                    fi

                    if [ ! -z "$desc" ]; then
                        echo -n "$desc"
                    fi

                    echo
                done

                echo

                ;;

            *)
                echo
                echo "usage: $myname service { action }"
                echo
                echo "Available actions:"
                echo
                echo "    disable Disable a service"
                echo "    enable  Enable a service"
                echo "    list    List available services"
                echo
                ;;

        esac

        ;;

    config)

        #
        # Actions related to config mode
        #

        case $action in

            set)
                name=$3
                value=$4

                if [ -z "$name" ]; then
                    doerror 1 "config setting must be specified"
                fi

                if [ -z "$value" ]; then
                    doerror 1 "config value must be specified"
                fi

                path=$(echo $name | tr . /)
                type=$(echo $name | cut -d. -f1)

                if [ -z "$(echo $type | grep -e 'vars' -e 'core')" ]; then
                    doerror 1 "setting prefix must be 'core' or 'vars'"
                fi

                mkdir -p "$etcdir/conf/$(dirname $path)"
                echo "$value" > "$etcdir/conf/$path"
                ;;

            get)
                name=$3

                if [ -z "$name" ]; then
                    (
                        cd "$etcdir/conf"
                        for f in $(find . -type f); do
                            path=$(echo $f | cut -b3-)
                            echo $(echo $path | tr / .) = $(cat $f)
                        done
                    )
                elif [ ! -f "$etcdir/conf/$(echo $name | tr . /)" ]; then
                    doerror 1 "setting doesn't exist '$name'"
                else
                    cat "$etcdir/conf/$(echo $name | tr . /)"
                fi
                ;;

            unset)
                name=$3

                if [ ! -f "$etcdir/conf/$(echo $name | tr . /)" ]; then
                    doerror 1 "setting doesn't exist '$name'"
                fi

                rm "$etcdir/conf/$(echo $name | tr . /)"
                ;;

            *)
                echo
                echo "usage: $myname config { action }"
                echo
                echo "    get    Get the value of a specific setting, or all settings"
                echo "    set    Set the value of a setting"
                echo "    unset  Delete a setting"
                echo
                exit 1
                ;;

        esac
        ;;

    zone|zones)

        #
        # Actions related to zones
        #

        case $action in

            define)
                zone=$3
                defaction=$4
                source=$5
                desc=$6

                zonedir="$etcdir/role.active/zones/$zone"

                if [ -d "$zonedir" ]; then
                    doerror 1 "zone already defined '$zone'"
                fi

                if [ ! "$defaction" = "allow" -a ! "$defaction" = "deny" ]; then
                    doerror 1 "zone default action must be 'allow' or 'deny', '$defaction' specified"
                fi

                if [ -z "$source" ]; then
                    doerror 1 "zone must define a source address/network"
                fi

                mkdir -p "$zonedir/services/local" "$zonedir/services/remote"
                echo $defaction > "$zonedir/default_action"

                for src in $(echo $source); do
                    echo "$src" >> "$zonedir/sources"
                done

                if [ ! -z "$desc" ]; then
                    echo "$desc" > "$zonedir/description"
                fi
                ;;

            list)
                for zone in $(ls -1 "$etcdir/role.active/zones"); do
                    zonedir="$etcdir/role.active/zones/$zone"
                    desc=""
                    if [ -f "$zonedir/description" ]; then
                        desc=$(head -n1 "$zonedir/description")
                    fi
                    echo -n "  "
                    printf '%-15s' "$zone"
                    echo $desc
                done
                ;;

            undefine)
                zone=$3
                zonedir="$etcdir/role.active/zones/$zone"

                if [ ! -d "$zonedir" ]; then
                    doerror 1 "zone hasn't been defined '$zone'"
                fi

                rm -r "$zonedir"
                ;;

            *)
                echo
                echo "usage: $myname $mode { action }"
                echo
                echo "    define    Define a new zone"
                echo "    list      Get a list of all zones for the current roll"
                echo "    undefine  Undefine (delete) an existing zone"
                echo
                exit 1
                ;;

        esac

        ;;

    *)
        echo "usage: $myname { config | role[s] | rules | service[s] | zone[s] }"
        exit 1
        ;;

esac

